version: '3'

######## 项目依赖的环境，启动项目之前要先启动此环境 #######

services:
#zookeeper是kafka的依赖
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    environment:
      # 时区上海
      TZ: Asia/Shanghai
    ports:
      - 2181:2181

  #消息队列
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - 9092:9092
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=kafka
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true
      - TZ=Asia/Shanghai
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://192.168.2.62:9092
      - KAFKA_LISTENERS=PLAINTEXT://192.168.2.62:9092
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper

  kafka-manager:
    image: sheepkiller/kafka-manager:latest
    container_name: kafka-manager
    hostname: kafka-manager
    ports:
      - "9000:9000"
    links: # 连接本compose文件创建的container
      - kafka
    external_links: # 连接本compose文件以外的container
      - zookeeper
    environment:
      ZK_HOSTS: "zookeeper:2181"
    depends_on:
      - zookeeper
      - kafka