// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.5
// source: ack.proto

package main

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AckBuild struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Area     string `protobuf:"bytes,1,opt,name=area,proto3" json:"area,omitempty"`
	MinMapId string `protobuf:"bytes,2,opt,name=minMapId,proto3" json:"minMapId,omitempty"`
	Uid      uint64 `protobuf:"varint,3,opt,name=uid,proto3" json:"uid,omitempty"`
	MapType  int32  `protobuf:"varint,4,opt,name=mapType,proto3" json:"mapType,omitempty"`
	X        int64  `protobuf:"varint,8,opt,name=x,proto3" json:"x,omitempty"`
	Y        int64  `protobuf:"varint,9,opt,name=y,proto3" json:"y,omitempty"`
}

func (x *AckBuild) Reset() {
	*x = AckBuild{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ack_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AckBuild) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AckBuild) ProtoMessage() {}

func (x *AckBuild) ProtoReflect() protoreflect.Message {
	mi := &file_ack_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AckBuild.ProtoReflect.Descriptor instead.
func (*AckBuild) Descriptor() ([]byte, []int) {
	return file_ack_proto_rawDescGZIP(), []int{0}
}

func (x *AckBuild) GetArea() string {
	if x != nil {
		return x.Area
	}
	return ""
}

func (x *AckBuild) GetMinMapId() string {
	if x != nil {
		return x.MinMapId
	}
	return ""
}

func (x *AckBuild) GetUid() uint64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *AckBuild) GetMapType() int32 {
	if x != nil {
		return x.MapType
	}
	return 0
}

func (x *AckBuild) GetX() int64 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *AckBuild) GetY() int64 {
	if x != nil {
		return x.Y
	}
	return 0
}

var File_ack_proto protoreflect.FileDescriptor

var file_ack_proto_rawDesc = []byte{
	0x0a, 0x09, 0x61, 0x63, 0x6b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x63, 0x69, 0x74,
	0x79, 0x1a, 0x0a, 0x63, 0x69, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xf3, 0x01,
	0x0a, 0x08, 0x41, 0x63, 0x6b, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x61, 0x72,
	0x65, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x61, 0x72, 0x65, 0x61, 0x12, 0x1a,
	0x0a, 0x08, 0x6d, 0x69, 0x6e, 0x4d, 0x61, 0x70, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x6d, 0x69, 0x6e, 0x4d, 0x61, 0x70, 0x49, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69,
	0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x18, 0x0a, 0x07,
	0x6d, 0x61, 0x70, 0x54, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x6d,
	0x61, 0x70, 0x54, 0x79, 0x70, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x49,
	0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x49, 0x64,
	0x12, 0x33, 0x0a, 0x0b, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x11, 0x2e, 0x63, 0x69, 0x74, 0x79, 0x2e, 0x42, 0x75, 0x69,
	0x6c, 0x64, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x0b, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x20, 0x0a, 0x03, 0x6f, 0x70, 0x74, 0x18, 0x07, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x0e, 0x2e, 0x63, 0x69, 0x74, 0x79, 0x2e, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x4f,
	0x70, 0x74, 0x52, 0x03, 0x6f, 0x70, 0x74, 0x12, 0x0c, 0x0a, 0x01, 0x78, 0x18, 0x08, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x01, 0x78, 0x12, 0x0c, 0x0a, 0x01, 0x79, 0x18, 0x09, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x01, 0x79, 0x42, 0x08, 0x5a, 0x06, 0x2e, 0x2f, 0x3b, 0x64, 0x74, 0x6f, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_ack_proto_rawDescOnce sync.Once
	file_ack_proto_rawDescData = file_ack_proto_rawDesc
)

func file_ack_proto_rawDescGZIP() []byte {
	file_ack_proto_rawDescOnce.Do(func() {
		file_ack_proto_rawDescData = protoimpl.X.CompressGZIP(file_ack_proto_rawDescData)
	})
	return file_ack_proto_rawDescData
}

var file_ack_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_ack_proto_goTypes = []interface{}{
	(*AckBuild)(nil), // 0: city.AckBuild
}
var file_ack_proto_depIdxs = []int32{
	1, // 0: city.AckBuild.buildStatus:type_name -> city.BuildStatus
	2, // 1: city.AckBuild.opt:type_name -> city.BuildOpt
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_ack_proto_init() }
func file_ack_proto_init() {
	if File_ack_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_ack_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AckBuild); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ack_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ack_proto_goTypes,
		DependencyIndexes: file_ack_proto_depIdxs,
		MessageInfos:      file_ack_proto_msgTypes,
	}.Build()
	File_ack_proto = out.File
	file_ack_proto_rawDesc = nil
	file_ack_proto_goTypes = nil
	file_ack_proto_depIdxs = nil
}
